version: '3'
services:
 opa:
   build: 
      context: ./opa
      dockerfile: Dockerfile

   image: opa:latest
   ports:
     - "8181:8181"
   networks:
     - mynetwork
 trino:
   build: 
      context: ./trino
      dockerfile: Dockerfile
   image: trino_plugin:latest
   ports:
     - "8080:8080"
   networks:
     - mynetwork
 abac_api:
   build: 
      context: ./abac_api
      dockerfile: Dockerfile
   image: abac_api:latest
   ports:
     - "8081:8081"
   networks:
     - mynetwork
networks:
  mynetwork:
    driver: bridge