version: '3'
services:
 opa:
   build: ./ # Dockerfile local dir
   ports:
     - "8181:8181"
   networks:
     - mynetwork
 trino:
   image: trino:opa-plugin
   ports:
     - "8080:8080"
   networks:
     - mynetwork

networks:
  mynetwork:
    driver: bridge